# Generated by Django 5.2.8 on 2025-11-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner_type', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('super_buildup_area_sqft', models.FloatField()),
                ('carpet_area_sqft', models.FloatField()),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_properties', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('super_buildup_area_sqft', models.FloatField()),
                ('carpet_area_sqft', models.FloatField()),
                ('owner_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_properties', to='api.customer')),
            ],
        ),
    ]
